add basic deployment and healtcheck

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -2,12 +2,16 @@ name: CI / CD
 
 on:
   push:
-  pull_request:
+    paths:
+      - 'api/**'
+      - '.github/workflows/cicd.yml'
+  workflow_dispatch:
 
 jobs:
   build-and-test:
     name: Build and Test
     runs-on: ubuntu-latest
+
 
     steps:
     - name: Check out the repository
@@ -21,3 +25,38 @@ jobs:
 
     - name: Clean up
       run: docker-compose down
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: test
+    if: github.ref == 'refs/heads/develop'
+    steps:
+
+    - name: Deploy to EC2
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{ secrets.HOST }}
+        username: ${{ secrets.USERNAME }}
+        key: ${{ secrets.SSH_KEY }}
+        script: |
+          cd amazonia360/amazonia-360
+          git pull
+          docker-compose down
+          docker-compose up -d api --build
+
+  health-check:
+    runs-on: ubuntu-latest
+    needs: deploy
+    if: github.ref == 'refs/heads/develop'
+    steps:
+      - name: Health Check
+        run: |
+          response=$(curl -s ${{ secrets.HEALTHCHECK }})
+          if [[ "$response" == *"status: ok"* ]]; then
+            echo "Health check passed"
+          else
+            echo "Health check failed"
+            exit 1
+          fi
+
+
